spring:
  application:
    name: api-saldo
  datasource:
    url: jdbc:postgresql://localhost:5432/saldo_db
    username: admin
    password: admin123
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: false
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

app:
  timezone: America/Sao_Paulo

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
